apiVersion: apps/v1
kind: Deployment
metadata:
  name: kriptografi-saas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kriptografi-saas
  template:
    metadata:
      labels:
        app: kriptografi-saas
    spec:
      containers:
        - name: kriptografi-saas
          image: kriptografi-saas:latest
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: sqlite-storage
              mountPath: /tmp
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: sqlite-pvc