apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kriptografi-saas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kriptografi-saas-deployment
  minReplicas: 1
  maxReplicas: 300
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80