apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: kriptografi-saas
spec:
  source:
    type: Git
    git:
      uri: https://github.com/ameliashintadewi0305-ship-it/kriptografi-saas.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: 'kriptografi-saas:latest'