apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kriptografi-saas-hpa
spec:
  scaleTargetRef:
    apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    name: kriptografi-saas
  minReplicas: 1 # Jumlah pod minimum saat beban rendah
  maxReplicas: 100 # Atur ke nilai yang sangat tinggi, atau sesuai dengan batas cluster
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Target penggunaan CPU rata-rata 50%